feat(ui): adding footer
NodeSecure/preview pull request #8
Opened 2021-12-27 15:34 UTC by MehdiHan

2021-12-28 13:50 UTC, MehdiHan commented
Adding footer markdown directly in Layout Component

2021-12-28 14:12 UTC, tony-go commented
Thanks @MehdiHan 👏 

I'll review it asap ^^

2021-12-30 08:01 UTC, tony-go requested changes
Thanks a lot for this 🙌 👏 

Didn't check the render yet. Could you join a screenshot?

2021-12-30 08:01 UTC, tony-go commented on components/Layout.tsx
> +          🕸 Powered by NodeSecure -{" "}
I was thinking about the logo of the organization.

2021-12-30 08:41 UTC, MehdiHan commented on components/Layout.tsx
> +      <footer>
Np i'll fix it today

2021-12-30 09:41 UTC, MehdiHan commented
Hi @tony-go, 

Changes requested are done, i'm available if you need something else about this issue.
Feel free to ask me.

![screenshoot_01](https://user-images.githubusercontent.com/53506859/147739930-e829de03-ed5c-4c4d-ac69-670c328664ac.jpg)
![screenshoot_02](https://user-images.githubusercontent.com/53506859/147739925-c49d6bbd-2df9-435f-a527-25145c54a54f.jpg)

2021-12-30 12:25 UTC, fraxken approved these changes
LGTM

2021-12-30 13:03 UTC, Kawacrepe commented
lgtm ! Thank's for your contribution

2021-12-30 15:06 UTC, tony-go approved these changes

2021-12-30 15:19 UTC, merged